### ISSUE TITLE
Missing Icons on Windows 10 22H2

### ISSUE THREAD

**Issue by D-Maxwell** [jpbandroid/TextPad#2]
![image](https://github.com/jpbandroid/TextPad/assets/98100481/436bbf88-e521-4706-a6c8-cfc90036dd33)

I think this speaks for itself.

**Comment by errortek** [comment]
> ![image](https://user-images.githubusercontent.com/98100481/284076233-436bbf88-e521-4706-a6c8-cfc90036dd33.png)
> 
> I think this speaks for itself.

yeah, I know of this issue and I had it myself :/
It's only because this uses a custom font to render some of the icons, I've attached the font here (you have to unzip the zip to get the font file though, as GitHub doesn't support attaching ttf files): [WordPadIcons.zip](https://github.com/jpbandroid/TextPad/files/13403968/WordPadIcons.zip)
